### ISSUE TITLE
ERROR -- : getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by rahul** [camelpunch/ungulate#19]
I have this in my config file,

``` ruby
Ungulate.configure do |config|
  config.access_key_id = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
  config.secret_access_key = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

  config.queue_name = 'my_unique_queue_name'
  config.queue_server = 'us-east-1.amazonaws.com'
  config.s3_region = 'ap-southeast-1'

  config.server_sleep = 2 # seconds
end
```

When I run the the ungulate server with this config file, I keep getting this error message,

E, [2012-04-01T21:48:39.842986 #41008] ERROR -- : getaddrinfo: nodename nor servname provided, or not known

---

After digging into the unugulate code, I noticed that in the SqsMessageQueue.initialize, there is

``` ruby
@queue_url = @sqs.create_queue(name).body['QueueUrl']
```

Since I had already created a queue through the AWS console, I commented that line and set 

``` ruby
@queue_url = "queue_url_given_by_amazon"
```

When I start the server after this change, the I see something new for a change

``` ruby
I, [2012-04-01T21:54:43.220589 #41029]  INFO -- : Checking for job on 'my_unique_queue_name'
# A pretty long wait, and then we are back to
E, [2012-04-01T21:48:39.891356 #41008] ERROR -- : getaddrinfo: nodename nor servname provided, or not known
I, [2012-04-01T21:54:43.220589 #41029]  INFO -- : Checking for job on 'my_unique_queue_name'
E, [2012-04-01T21:48:39.891356 #41008] ERROR -- : getaddrinfo: nodename nor servname provided, or not known
.
.
.
```

I am not sure if this is an ungulate configuration or something else. Any help here?

**Comment by rahul** [comment]
I just noticed that this error comes first when I try to enqueue a job after uploading an image to S3.

This is the stacktrace

``` ruby
excon (0.13.2) lib/excon/socket.rb:26:in `getaddrinfo'
excon (0.13.2) lib/excon/socket.rb:26:in `connect'
excon (0.13.2) lib/excon/socket.rb:16:in `initialize'
excon (0.13.2) lib/excon/ssl_socket.rb:31:in `initialize'
excon (0.13.2) lib/excon/connection.rb:322:in `new'
excon (0.13.2) lib/excon/connection.rb:322:in `socket'
excon (0.13.2) lib/excon/connection.rb:168:in `request_kernel'
excon (0.13.2) lib/excon/connection.rb:97:in `request'
fog (1.3.1) lib/fog/core/connection.rb:20:in `request'
fog (1.3.1) lib/fog/aws/sqs.rb:137:in `request'
fog (1.3.1) lib/fog/aws/requests/sqs/send_message.rb:26:in `send_message'
/Users/rahul/.rvm/gems/ruby-1.9.3-head/bundler/gems/ungulate-713118221469/lib/ungulate/sqs_message_queue.rb:49:in `push'
/Users/rahul/.rvm/gems/ruby-1.9.3-head/bundler/gems/ungulate-713118221469/lib/ungulate/file_upload.rb:10:in `enqueue'
```

My query_url = "https://queue.amazonaws.com/MY_AMAZON_ACCOUNT_NUMBER/my_unique_queue_name"
and path_from_query_url = "/MY_AMAZON_ACCOUNT_NUMBER/my_unique_queue_name"

**Comment by rahul** [comment]
I am an idiot. Problem resolved.

Missed 'sqs' at the front of 'us-east-1.amazonaws.com'

So config.queue_server = 'sqs.us-east-1.amazonaws.com'

**Comment by camelpunch** [comment]
Glad you got it sorted. The call to create_queue creates a queue only if it's not already present.
