### ISSUE TITLE
When used in along side devise, it breaks.

### ISSUE THREAD

**Issue by railsadict** [camelpunch/ungulate#2]
I've got the below gems installed on my rails app and as soon as i add ungulate devise breaks.

gem 'rails', '3.0.4'
gem 'sqlite3'
gem 'devise'
gem 'kaminari'
gem 'ungulate'

This seems to be specific to ungulate, not sure weather devise or ungulate is causing the issue however i thought i would mention it.

Routing Error
wrong constant name Devise/sessionsController

Started GET "/accounts/sign_out" for 127.0.0.1 at Tue Feb 22 06:50:52 +0000 2011
ActionController::RoutingError (wrong constant name Devise/sessionsController):
  Rendered /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.4/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (0.9ms)

Started GET "/accounts/edit" for 127.0.0.1 at Tue Feb 22 06:56:40 +0000 2011
ActionController::RoutingError (wrong constant name Devise/registrationsController):
  Rendered /usr/lib/ruby/gems/1.8/gems/actionpack-3.0.4/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (0.8ms)

Thanks.

**Comment by camelpunch** [comment]
Haven't got round to reproducing this yet, but try adding these lines to your application's Gemfile:

```
gem 'right_http_connection', :git => 'https://github.com/rightscale/right_http_connection.git'
gem 'right_aws', :git => 'https://github.com/rightscale/right_aws.git'
```

The released version of right_aws isn't ActiveSupport 3 friendly.

**Comment by railsadict** [comment]
thank you for the quick response, i will try this tonight :)

**Comment by camelpunch** [comment]
Closing this as I'm assuming the latest RightAWS worked for you. Reopen if not!
