### ISSUE TITLE
Unable to connect to SQS anymore (403)

### ISSUE THREAD

**Issue by rahul** [camelpunch/ungulate#20]
Recently we found out that our ungulate server has been unable to connect to Amazon SQS for a few days. The server was started in April and until last week, there weren't any communication issues between the server and SQS. But then, the following errors started coming up,

```
I, [2012-09-06T16:24:53.307521 #23421]  INFO -- : Checking for job on images-uploader-queue-name
E, [2012-09-06T16:24:53.338250 #23421] ERROR -- : Expected(200) <=> Actual(403 Forbidden)
  request => {:connect_timeout=>60, :headers=>{"Content-Type"=>"application/x-www-form-urlencoded", "Host"=>"sqs.ap-southeast-1.amazonaws.com:443", "Content-Length"=>234}, :instrumentor_name=>"excon", :mock=>false, :read_timeout=>60, :retry_limit=>4, :ssl_ca_file=>"/home/ec2-user/webapps/our_app/shared/bundle/ruby/1.9.1/gems/excon-0.13.2/data/cacert.pem", :ssl_verify_peer=>true, :write_timeout=>60, :host=>"sqs.ap-southeast-1.amazonaws.com", :path=>"/:443/XXXXXXXXX/images-uploader-queue-name", :port=>"443", :query=>nil, :scheme=>"https", :body=>"AWSAccessKeyId=XXXXXXXXXXXXXXXX&Action=ReceiveMessage&AttributeName=All&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2012-09-06T10%3A54%3A53Z&Version=2009-02-01&Signature=YRAb36ql4Kr1Jr7WO8hHQVfwN%2BypJVJuFZttsdGogvI%3D", :expects=>200, :idempotent=>nil, :method=>"POST", :response_block=>#<Proc:0x91938dc@/home/ec2-user/webapps/our_app/shared/bundle/ruby/1.9.1/gems/fog-1.3.1/lib/fog/core/connection.rb:16 (lambda)>}
  response => #<Excon::Response:0x919d56c @body="<?xml version=\"1.0\"?><ErrorResponse xmlns=\"http://queue.amazonaws.com/doc/2009-02-01/\"><Error><Type>Sender</Type><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message><Detail/></Error><RequestId>60e9e2f6-5fa2-571a-853d-aa34dc9fe747</RequestId></ErrorResponse>", @headers={"x-amzn-RequestId"=>"60e9e2f6-5fa2-571a-853d-aa34dc9fe747", "Content-Type"=>"text/xml", "Content-Length"=>"436"}, @status=403>
```

No changes were done on the AWS console, no code pushes, or gem updates. The server simply started receiving 403s. I tried to Google a lot but it was of no use.

We are using ungulate @ commit#7131182214

In your lates commit, the README says

```
Note that Ungulate::FileUpload has now been superseded by the official Amazon SDK version
```

We don't understand what that means

**Comment by camelpunch** [comment]
Hi Rahul

When you have sudden failures like this, it's good to check:
- Your system clock hasn't drifted
- Your AWS access keys can still be used from the command line of the box
  in question (try the official AWS SDK for Ruby on github through IRB)

If both of these yield nothing, let me know and we can try to debug it
together some time.

Cheers

Andrew

**Comment by rahul** [comment]
Problem finally solved.
1. Had to add "require 'ungulate/file_upload" in config/initializers/ungulate.rb in spite of having a "require 'ungulate'" already in place.
2. bundle install got new exconn, fog and related gems.

Both system clock and keys were fine though.

Thank you for your help!
