### ISSUE TITLE
Seems not to work in ruby 1.9.2

### ISSUE THREAD

**Issue by marcofognog** [camelpunch/ungulate#6]
Is that right?

**Comment by camelpunch** [comment]
Not right now. I'm working on it though, and it should be ready in a few days.

**Comment by camelpunch** [comment]
Pushed some commits to master that should fix things for 1.9.2. However, it's now depending on both Fog and right_aws, which is a bit bloaty. Also, due to the way Fog works, you'll need an extra config option if you want to use a non-default s3 region e.g.:

```
Ungulate.configure do |config|
  config.s3_region = 'eu-west-1'
end
```

I'd like to replace the SQS code with a Fog version before releasing a new gem version. Let me know how these changes work. Thanks for the heads up!

**Comment by marcofognog** [comment]
Cool, I'll give it a try, and get back to you.

**Comment by marcofognog** [comment]
All right, working on ruby 1.9, except for some failing tests.
I setup my security credentials, and the bucket, but I am not that familiar with the Amazon API, so for now, just report is the most I can do in this case.

 When I run Ungulate            # features/step_definitions/command_steps.rb:4
      Expected([200, 206]) <=> Actual(301 Moved Permanently)
        request => {:connect_timeout=>60, :headers=>{"Date"=>"Tue, 01 Nov 2011 14:28:19 +0000", "Authorization"=>"AWS AKIAIR7EdwWQJKZPWA5GBN4Q:0+DeAOhx6cKAswdWecfaUTbyiTbfu=", "Host"=>"platytest.s3-eu-west-1.amazonaws.com:443", "Content-Length"=>0}, :host=>"platytest.s3-eu-west-1.amazonaws.com", :mock=>nil, :path=>"/image.jpg", :port=>"443", :query=>nil, :read_timeout=>60, :scheme=>"https", :write_timeout=>60, :expects=>[200, 206], :idempotent=>true, :method=>"GET"}
        response => #<Excon::Response:0x00000004780768 @body="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><RequestId>C51CCC608E2365B2</RequestId><Bucket>platytest</Bucket><HostId>ajMQGL2ILshNXXf2WW1DRQEKjl85JMjnCoaRJOfgtg2fYDaneakJT0SSZFc3FhEAIYDedgHIHi</HostId><Endpoint>s3.amazonaws.com</Endpoint></Error>", @headers={"x-amz-request-id"=>"C51CCC608E2365B2", "x-amz-id-2"=>"ajMQGL2ILshNWdwwXXf2WW1DRQEKjl85JMjnYguyTubrtfUrUbytFtyQAPoOSSZFc3FhgHIHi", "Content-Type"=>"application/xml", "Transfer-Encoding"=>"chunked", "Date"=>"Tue, 01 Nov 2011 14:28:24 GMT", "Server"=>"AmazonS3"}, @status=301> (Excon::Errors::MovedPermanently)
      ./lib/ungulate/s3_storage.rb:43:in `retrieve'
      ./lib/ungulate/job.rb:16:in`process'
      ./lib/ungulate/server.rb:29:in `run'
      ./lib/ungulate/server.rb:19:in`run'
      ./features/step_definitions/command_steps.rb:15:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/command_steps.rb:14:in`times'
      ./features/step_definitions/command_steps.rb:14:in `/^I run Ungulate$/'
      features/cope_with_empty_queue.feature:8:in`When I run Ungulate'

**Comment by camelpunch** [comment]
I haven't sorted out testing on other people's machines yet, watch: https://github.com/camelpunch/ungulate/issues/5

**Comment by camelpunch** [comment]
bb9e888ce62ca9c10da99fd64c37965169324f4d adds the ability to configure the test queues and buckets to use when running the Cucumber suite. See the updated [config/ungulate.rb](https://github.com/camelpunch/ungulate/blob/master/config/ungulate.rb) for details. I'd appreciate it if you could let me know if Cucumber will run without failures now.

**Comment by marcofognog** [comment]
I am still not able to pass all cucumber tests, although the lib works fine in my app, so its not ruby version related.  I think you can close this issue.

**Comment by camelpunch** [comment]
Could you post a gist of your test output please?

**Comment by marcofognog** [comment]
Sorry for the late reply!
this is the error I get running the cucumber tests http://pastie.org/2883230
And yes, I configured acces_key and secret in the config/ungulate.rb,

**Comment by camelpunch** [comment]
Do you have latest master version? I made a change recently to stop taking access key / secret from ENV.

**Comment by marcofognog** [comment]
yeah, master, last commit -> 1245008

**Comment by camelpunch** [comment]
Could you post a version of your config/ungulate.rb with the sensitive values scrubbed out? Or email: andrew@camelpunch.com

**Comment by camelpunch** [comment]
Okay, could you please try again with the new commit I just pushed?

**Comment by marcofognog** [comment]
Tried again, no luck. Different error messages. If you'd like to take a look: http://pastie.org/2914759

**Comment by camelpunch** [comment]
This one looks like you're requesting a different region to the bucket you've configured. Could you please check your config.s3_region is set correctly? It looks like you need to set it to us-east-1, or try not setting it at all.

**Comment by marcofognog** [comment]
I included the following in th econfig file

config.s3_region = 'us-east-1'

but it still gives me the same error.

One of the params of the request is :
"Host"=>"platytest.s3-eu-west-1.amazonaws.com:443"
I guess that was supposed to be changed when I set the region, right?
Wierd is: you open Fog::Storage::AWS:Real we can see the default :region set to us-east-1
https://github.com/fog/fog/blob/master/lib/fog/aws/storage.rb

**Comment by marcofognog** [comment]
Wow, I just found out. I'll send you a patch soon.
